server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: jdbc:mysql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}?serverTimezone=GMT
  h2:
    console:
      enabled: false